/* istanbul ignore next */
import connectDatabase from '../connect';
import logger from '../utils/logger';

const { sequelize } = connectDatabase();

/* istanbul ignore next */
sequelize.query('update abbrevs set "photo"=null where true;')
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-almond.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%almond%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-coconut.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%coconut%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-avocado.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%avocado%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-canola.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%canola%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-hazelnut.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%hazelnut%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-sesame.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%sesame%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-soybean.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%soybean%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-sunflower.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%sunflower%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'oil-walnut.png\' where "Main" ilike \'oil\' and "Sub" iLike \'%walnut%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'apple-golden-delicious.png\' where "Main" ilike \'apples\' and "Sub" iLike \'%gold%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'apple-fuji.png\' where "Main" ilike \'apples\' and "Sub" iLike \'%fuji%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'zucchini.png\' where "Main" ilike \'squash\' and "Sub" iLike \'%zucchini%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'squash-crookneck.png\' where "Main" ilike \'squash\' and "Sub" iLike \'%crookneck%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'squash-butternut.png\' where "Main" ilike \'squash\' and "Sub" iLike \'%butternut%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'squash-spaghetti.png\' where "Main" ilike \'squash\' and "Sub" iLike \'%spaghetti%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'squash-all-varieties.png\' where "Main" ilike \'squash\' and "Sub" iLike \'%all variet%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'baby-formula.png\' where "Main" ilike \'infant formula\'and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'bread-pumpernickel.png\' where "Main" ilike \'bread\'and "Sub" iLike \'%pumpernickel%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'bread-raisin.png\' where "Main" ilike \'bread\'and "Sub" iLike \'%raisin%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'bread-italian.png\' where "Main" ilike \'bread\'and "Sub" iLike \'%italian%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'bread-pita.png\' where "Main" ilike \'bread\'and "Sub" iLike \'%pita%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'bread-naan.png\' where "Main" ilike \'bread\'and "Sub" iLike \'%naan%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'bread-white-toasted.png\' where "Main" ilike \'bread\'and "Sub" iLike \'%toasted%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'apple-granny-smith.png\' where "Main" ilike \'apples\' and "Sub" iLike \'%granny%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beef-back-rib.png\' where "Main" ilike \'beef\' and "Sub" iLike \'%rib%\' and "Sub" iLike \'%back%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pork-back-rib.png\' where "Main" ilike \'pork\' and "Sub" iLike \'%rib%\' and "Sub" iLike \'%back%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beef-rib.png\' where "Main" ilike \'beef\' and "Sub" iLike \'%rib%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pork-rib.png\' where "Main" ilike \'pork\' and "Sub" iLike \'%rib%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beef-ribeye.png\' where "Main" ilike \'beef\' and "Sub" iLike \'%ribeye%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beef-ground.png\' where "Main" ilike \'beef\' and "Sub" iLike \'%ground%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beef-round.png\' where "Main" ilike \'beef\' and "Sub" iLike \'%round%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beef-chuck.png\' where "Main" ilike \'beef\' and "Sub" iLike \'%chuck%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beef-top-loin.png\' where "Main" ilike \'beef\' and "Sub" iLike \'%loin%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'turkey.png\' where "Main" ilike \'turkey\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'apple.png\' where "Main" ilike \'apples\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'blueberry.png\' where "Main" ilike \'blueberries\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'blueberry.png\' where "Main" ilike \'blueberries\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'cherry.png\' where "Main" ilike \'cherries\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'avocado.png\' where "Main" ilike \'avocados\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'tomato.png\' where "Main" ilike \'tomatoes\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'strawberry.png\' where "Main" ilike \'strawberries\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'cabbage.png\' where "Main" ilike \'cabbage\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'asparagus.png\' where "Main" ilike \'asparagus\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'broccoli.png\' where "Main" ilike \'broccoli\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'banana.png\' where "Main" ilike \'bananas\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'cake.png\' where "Main" ilike \'cake\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'cauliflower.png\' where "Main" ilike \'cauliflower\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'cheese.png\' where "Main" ilike \'cheese\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'coffee.png\' where "Main" ilike \'coffee\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'cookies.png\' where "Main" ilike \'cookies\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'corn.png\' where "Main" ilike \'corn\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'croissant.png\' where "Main" ilike \'croissants\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'doughnut.png\' where "Main" ilike \'doughnuts\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'eggs.png\' where "Main" ilike \'egg\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'eggs.png\' where "Main" ilike \'eggs\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'eggplant.png\' where "Main" ilike \'eggplant\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'fig.png\' where "Main" ilike \'figs\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'granola.png\' where "Main" ilike \'granola\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'ice-cream-cone.png\' where "Main" ilike \'ice cream\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'ice-cream-cone.png\' where "Main" ilike \'ice creams\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'lemonade.png\' where "Main" ilike \'lemonade\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'carrot.png\' where "Main" ilike \'carrots\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'olive.png\' where "Main" ilike \'olives\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'orange.png\' where "Main" ilike \'orange juice\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'orange.png\' where "Main" ilike \'tangerines\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'orange.png\' where "Main" ilike \'oranges\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'onion.png\' where "Main" ilike \'onions\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pancakes.png\' where "Main" ilike \'pancakes\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'bell-pepper.png\' where "Main" ilike \'peppers\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'peach.png\' where "Main" ilike \'peaches\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pear.png\' where "Main" ilike \'pears\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pie.png\' where "Main" ilike \'pie\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pie.png\' where "Main" ilike \'pie crust\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pineapple.png\' where "Main" ilike \'pineapple\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pineapple.png\' where "Main" ilike \'pineapple juice\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'potatoes.png\' where "Main" ilike \'potatoes\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'pumpkin.png\' where "Main" ilike \'pumpkin\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'raspberries.png\' where "Main" ilike \'raspberries\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'rice.png\' where "Main" ilike \'rice\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'salami.png\' where "Main" ilike \'salami\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'soup.png\' where "Main" ilike \'soup\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'glass.png\' where "Main" ilike \'water\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beef.png\' where "Main" ilike \'beef\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'milk.png\' where "Main" ilike \'milk\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'chicken.png\' where "Main" ilike \'chicken\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'fish.png\' where "Main" ilike \'fish\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'ham.png\' where "Main" ilike \'pork\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'cereal.png\' where "Main" ilike \'cereals ready-to-eat\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'quaker-apple-cinnamon.png\' where "Main" ilike \'cereals\' and "Sub" iLike \'QUAKER, Instant Oatmeal, Apple and Cinnamon, reduced sugar\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'quaker-banana-bread.png\' where "Main" ilike \'cereals\' and "Sub" iLike \'QUAKER, Instant Oatmeal, Banana Bread, dry\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'quaker-apple-cinnamon.png\' where "Main" ilike \'cereals\' and "Sub" iLike \'QUAKER, Instant Oatmeal, apples and cinnamon, dry\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'quaker-cinnamon-spice.png\' where "Main" ilike \'cereals\' and "Sub" iLike \'QUAKER, Instant Oatmeal, Cinnamon-Spice, dry\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'quaker-instant-maple-brown-sugar.png\' where "Main" ilike \'cereals\' and "Sub" iLike \'QUAKER, Instant Oatmeal, maple and brown sugar, dry\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'quaker-raisin-date-walnut.png\' where "Main" ilike \'cereals\' and "Sub" iLike \'QUAKER, Instant Oatmeal, raisins, dates and walnuts, dry\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'quaker-variety.png\' where "Main" ilike \'cereals\' and "Sub" iLike \'QUAKER%\' and "Sub" ilike \'%oatmeal%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'jam-jar.png\' where "Main" ilike \'babyfood\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'game-ribs.png\' where "Main" ilike \'lamb\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'game-ribs.png\' where "Main" ilike \'veal\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'snacks.png\' where "Main" ilike \'snacks\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'fast-food.png\' where "Main" ilike \'fast foods\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'nuts.png\' where "Main" ilike \'nuts\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'candy.png\' where "Main" ilike \'candies\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'yogurt.png\' where "Main" ilike \'yogurt\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'wine-red.png\' where "Main" ilike \'alcoholic beverage\' and "Sub" ilike \'%wine%\' and "Sub" iLike \'%red%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'chickpeas.png\' where "Main" ilike \'chickpeas%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'half-and-half.png\' where "Sub" ilike \'%half and half%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-black.png\' where "Main" ilike \'beans\' and "Sub" ilike \'%black%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-kidney.png\' where "Main" ilike \'beans\' and "Sub" ilike \'%kidney%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-pinto.png\' where "Main" ilike \'beans\' and "Sub" ilike \'%pinto%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-baked.png\' where "Main" ilike \'beans\' and "Sub" ilike \'%baked%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-lima.png\' where "Main" ilike \'beans\' and "Sub" ilike \'%lima%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-lima.png\' where "Main" ilike \'lima beans\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-green.png\' where "Main" ilike \'beans\' and "Sub" ilike \'%snap%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-green.png\' where "Main" ilike \'beans\' and "Sub" ilike \'%green%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beans-great-northern.png\' where "Main" ilike \'beans\' and "Sub" ilike \'%great northern%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'beer.png\' where "Main" ilike \'alcoholic beverage\' and "Sub" ilike \'%beer%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'wine-white.png\' where "Main" ilike \'alcoholic beverage\' and "Sub" ilike \'%wine%\' and photo is null;'))
  .then(() => sequelize.query('update abbrevs set "photo"=\'keebler-logo.png\' where "Main" ilike \'keebler\' and photo is null;'))

  .then(() => sequelize.query('select count(*) from abbrevs where photo is null;'))
  .then(([[{ count }]]) => logger.verbose(`\n\n${count} abbrevs left unassigned`))
  .then(() => logger.verbose('\n\nDone'))
  .then(() => process.exit())
  .catch((er) => {
    logger.error(er.stack);
    process.exit();
  });
